name: Test - Custom Config
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    concurrency:
      group: "test-custom-config-${{ github.head_ref || github.ref }}"
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: ./
        with:
          client: nethermind-gnosis
          simulator: gnosis/rpc-compat
          workflow_artifact_upload: true
          client_config: |
            - client: nethermind-gnosis
              nametag: nethermind-gnosis-main
              dockerfile: git
              build_args:
                github: NethermindEth/nethermind
                tag: master
